# Generated by Django 5.2.9 on 2026-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlistproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ave_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
