# Generated by Django 5.2.7 on 2025-12-02 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordermodel_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
