# Generated by Django 5.2.7 on 2025-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_couponmodel_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
